### ISSUE TITLE
Option to exclude NFS mounts from being scanned by default

### ISSUE THREAD

**Issue by pc-galante** [aide/aide#62] opened 2019-12-06 19:14 UTC
Looking for an option to exclude NFS client mounts from being scanned (by default).

In large environments with many clients mounting the same shared NFS file system(s), hosts hammer the NFS server(s) and consume extra CPU resources.  With a few multi TB sized shares the scans can take more than 24 hours to complete resulting in more than one aide process running.  Provisioning into cloud providers where CPU, network and storage IOPS are billed will result in greatly inflated costs.

Performance impact of adding just a few RHEL/CentOS 7 hosts with default AIDE configuration can be seen on 10/2, 11/16 & 12/5 in perf graph:
![Screen Shot 2019-12-06 at 11 05 41 AM](https://user-images.githubusercontent.com/58606434/70348892-7d60d080-1818-11ea-9cac-9e39222b3a88.png)

**Comment by hvhaugwitz** [comment] 2019-12-06 21:41
Thanks for your feature request.

This is basically a duplicate of #39 . Hence i close this issue.

**Closed by hvhaugwitz** 2019-12-06 21:41 UTC
Labels: enhancement
