### ISSUE TITLE
@@include

### ISSUE THREAD

**Issue by Zugschlus** [aide/aide#38] opened 2019-06-04 17:10 UTC
This is https://sourceforge.net/p/aide/feature-requests/13/

Hi,

it would be great for the Debian packaging if it were
possible to @include entire directories like
/etc/aide/aide.conf.d/.

aide would have to take precautions to avoid including
backup files and other disabled files. In Debian, for
example, it is common to exclude files ending in
.dpkg-*. There are multiple approaches:

* Insist on a certain extension (.conf, for example)
* Having a regexp of allowed file names (settable at
compile time is acceptable, run time of course preferred)
* Having a regexp of file names to be ignored

This would allow packages to bring their own aide
configuration snippet and to have it enabled
automatically. The Debian aide packages currently
implement this behavior by having aide wrapped and the
real configuration file built just before aide is
invoked, but that's a fragile hack. Would be better to
have that functionality in aide proper.

Thanks for considering.

**Comment by Zugschlus** [comment] 2019-06-04 17:11
argh, duplicate, please close

**Comment by hvhaugwitz** [comment] 2019-06-09 17:42
Duplicate of #4

**Closed by hvhaugwitz** 2019-06-09 17:42 UTC
Labels: duplicate
