### ISSUE TITLE
src/db_disk.c:198:24: error: variable has incomplete type 'struct stat64'

### ISSUE THREAD

**Issue by hdatma** [aide/aide#1] opened 2019-03-07 17:49 UTC
```
In file included from src/db_disk.c:38:
./include/gen_list.h:75:66: warning: declaration of 'struct stat64' will not be visible outside of this function [-Wvisibility]
db_line* get_file_attrs(char* filename,DB_ATTR_TYPE attr, struct AIDE_STAT_TYPE *fs);
                                                                 ^
./config.h:47:24: note: expanded from macro 'AIDE_STAT_TYPE'
#define AIDE_STAT_TYPE stat64
                       ^
src/db_disk.c:173:51: warning: declaration of 'struct stat64' will not be visible outside of this function [-Wvisibility]
static int get_file_status(char *filename, struct AIDE_STAT_TYPE *fs) {
                                                  ^
./config.h:47:24: note: expanded from macro 'AIDE_STAT_TYPE'
#define AIDE_STAT_TYPE stat64
                       ^
src/db_disk.c:175:12: warning: implicit declaration of function 'lstat64' is invalid in C99 [-Wimplicit-function-declaration]
    sres = AIDE_LSTAT_FUNC(filename,fs);
           ^
./config.h:32:25: note: expanded from macro 'AIDE_LSTAT_FUNC'
#define AIDE_LSTAT_FUNC lstat64
                        ^
src/db_disk.c:198:24: error: variable has incomplete type 'struct stat64'
        struct AIDE_STAT_TYPE fs;
                              ^
src/db_disk.c:198:9: note: forward declaration of 'struct stat64'
        struct AIDE_STAT_TYPE fs;
               ^
./config.h:47:24: note: expanded from macro 'AIDE_STAT_TYPE'
#define AIDE_STAT_TYPE stat64
                       ^
 
```

**Comment by hvhaugwitz** [comment] 2019-03-08 08:24
Thanks for your bug report.

Unfortunately I'm not able to reproduce your issue. Can you please provide more information about how to reproduce your issue (e.g. platform, distribution, source version, exact commands you used, to build AIDE, ....)

**Comment by hdatma** [comment] 2019-03-08 09:57
macos

**Comment by hvhaugwitz** [comment] 2019-03-08 10:26
Can you please provide the `./configure` command you used?

**Comment by hdatma** [comment] 2019-03-08 11:53
```
config_options="--prefix=$prefix \
   --sysconfdir=$etc \
   --mandir=$man \
   --docdir=$doc \
   --disable-static \
   --disable-lfs \
   --with-mhash \
   --without-zlib \
   --without-gcrypt"; 
```

**Comment by hvhaugwitz** [comment] 2019-03-08 20:25
Still cannot reproduce your issue (on MaOS Mojave (10.14.3)) using your ./configure options:
```
./aide --version
Aide 0.16.1

Compiled with the following options:

WITH_MMAP
WITH_PCRE
WITH_LSTAT
WITH_READDIR
WITH_MHASH
CONFIG_FILE = “/etc/aide.conf”
```

**Comment by hdatma** [comment] 2019-03-08 21:28
I'

**Comment by hdatma** [comment] 2019-03-08 21:29
I'm on 10.3

**Comment by hdatma** [comment] 2019-03-08 21:33
Wait, what? WITH_LSTAT? Am I missing a library?

**Comment by hvhaugwitz** [comment] 2019-03-16 06:46
Please contact the [AIDE mailing list](https://www.ipi.fi/mailman/listinfo/aide) to get more help from other MacOS users.

I close this issue for now. It can be reopened later if needed.

**Closed by hvhaugwitz** 2019-03-16 06:46 UTC
Labels: bug, moreinfo, unreproducible

**Comment by hdatma** [comment] 2019-03-16 09:31
[stat.h.txt](https://github.com/aide/aide/files/2973720/stat.h.txt)

**Comment by hvhaugwitz** [comment] 2019-03-17 21:06
I'm not a MacOS user and only have access to a Mac occasionally, so please contact the [AIDE mailing list](https://www.ipi.fi/mailman/listinfo/aide) to get more help from other MacOS users.
